# GitHub Dark High Contrast Theme
# vim:set ft=tmux:

set-option -g status "on"

set -g default-terminal "tmux-256color"

# Start window and pane indices at 1.
set -g base-index 1
set -g pane-base-index 0

# Length of tmux status line
set -g status-left-length 30
set -g status-right-length 150

# Background and Foreground
set -g @bg_color "#0a0c10"      # Background
set -g @fg_color "#f0f3f6"      # Foreground

# Color Palette
set -g @blue "#71b7ff"
set -g @red "#ff6a69"
set -g @green "#09b43a"
set -g @orange "#f0b72f"
set -g @yellow "#fbd669"
set -g @purple "#dbb7ff"
set -g @overlay1 "#9ea7b3"
set -g @surface0 "#525964"
set -g @surface1 "#272b33"

# Default statusbar color
set-option -g status-style "bg=#{@surface1},fg=#{@overlay1}"

# Default window title colors
set-window-option -g window-status-style "bg=#{@surface1},fg=#{@overlay1}"

# Default window with an activity alert
set-window-option -g window-status-activity-style "bg=#{@blue},fg=#{@bg_color},bold"

# Active window title colors
set-window-option -g window-status-current-style "bg=#{@green},fg=#{@surface1},bold"

# Set active pane border color
set-option -g pane-active-border-style "fg=#{@surface0}"

# Set inactive pane border color
set-option -g pane-border-style "fg=#{@surface1}"

# Message info
set-option -g message-style "bg=#{@surface1},fg=#{@yellow}"

# Writing commands inactive
set-option -g message-command-style "bg=#{@green},fg=#{@bg_color},bold"

# Bell
set-window-option -g window-status-bell-style "bg=#{@surface1},fg=#{@yellow}"

# Status Left
set-option -g status-left "\
#[fg=#{@overlay1}, bg=#{@surface1}]#{?client_prefix,#[fd=#{@red}],} ❐ #S \
#[fg=#{@overlay1}, bg=#{@surface1}]#{?client_prefix,#[fg=#{@red}],}#{?window_zoomed_flag, 🔍,} "

# Status Right
set-option -g status-right "\
#[fg=#{@overlay1}, bg=#{@surface1}] %b %d '%y\
#[fg=#{@overlay1}, bg=#{@surface1}] | %H:%M \
#[fg=#{@overlay1}, bg=#{@surface1}]"

# [fg=#{@surface1}, bg=#{@bg_color}]\
# Window Status Current Format
set-window-option -g window-status-current-format "\
#[fg=#{@surface1}, bg=#{@blue}] #I -\
#[fg=#{@surface1}, bg=#{@blue}, bold] #W "

# Window Status Format
set-window-option -g window-status-format "\
#[fg=#{@overlay1}, bg=#{@surface1}] #I -\
#[fg=#{@overlay1}, bg=#{@surface1}, bold] #W "
