# GitHub Dark High Contrast Theme
# vim:set ft=tmux:

# Background and Foreground
set -g @bg_color "#0a0c10"      # Background
set -g @fg_color "#f0f3f6"      # Foreground

# Color Palette
set -g @blue      "#71b7ff"
set -g @red      "#ff6a69"
set -g @green     "#09b43a"
set -g @orange    "#f0b72f"
set -g @yellow    "#fbd669"
set -g @purple     "#dbb7ff"
set -g @overlay1  "#9ea7b3"
set -g @surface0  "#525964"
set -g @surface1  "#272b33"


# Status Bar
set -g status-style "bg=#{@surface1},fg=#{@overlay1}"

# Active Window Style
set -g window-status-current-style "bg=#{@blue},fg=#{@bg_color},bold"

# Inactive Window Style
set -g window-status-style "bg=#{@surface1},fg=#{@overlay1}"

# Pane Borders
set -g pane-border-style "fg=#{@surface0}"
set -g pane-active-border-style "fg=#{@blue}"

# Message Text (e.g., when displaying prompts)
set -g message-style "bg=#{@surface1},fg=#{@red}"

# Command Prompt
set -g message-command-style "bg=#{@surface1},fg=#{@purple}"

# Mode Style (e.g., copy mode)
set -g mode-style "bg=#{@surface1},fg=#{@yellow}"

# Clock Mode Colour
# set -g clock-mode-colour "#{@purple}"
set -g clock-mode-style 24

##### Key Bindings #####

# Reload Tmux configuration using Prefix + r
bind-key r source-file ~/.tmux.conf \; display-message "Tmux configuration reloaded!"

##### Additional Configurations #####

# Ensure 256-color is supported
set -g default-terminal "tmux-256color"
